/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface TrafficClassification {
    attackType: AttackType;
    riskLevel: RiskLevel;
}
export interface DetectionEvent {
    featureSummary: FeatureSummary;
    timestamp: Time;
    classification: TrafficClassification;
}
export interface FeatureSummary {
    duration: bigint;
    destinationPortRange: bigint;
    packets: bigint;
    sourcePortRange: bigint;
    protocolTcpRatio: number;
    protocolIcmpRatio: number;
    protocolUdpRatio: number;
    bytes: bigint;
}
export interface UserProfile {
    name: string;
}
export enum AttackType {
    dos = "dos",
    r2l = "r2l",
    u2r = "u2r",
    normal = "normal",
    probe = "probe"
}
export enum RiskLevel {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearDetectionHistory(): Promise<void>;
    detectTraffic(features: FeatureSummary): Promise<TrafficClassification>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDetectionHistory(): Promise<Array<DetectionEvent>>;
    getDetectionHistoryByAttackType(): Promise<Array<AttackType>>;
    getDetectionHistoryByBytes(): Promise<Array<FeatureSummary>>;
    getDetectionHistoryByDestinationPortRange(): Promise<Array<FeatureSummary>>;
    getDetectionHistoryByDuration(): Promise<Array<FeatureSummary>>;
    getDetectionHistoryByIcmpRatio(): Promise<Array<FeatureSummary>>;
    getDetectionHistoryByPackets(): Promise<Array<FeatureSummary>>;
    getDetectionHistoryByRiskLevel(): Promise<Array<RiskLevel>>;
    getDetectionHistoryBySourcePortRange(): Promise<Array<FeatureSummary>>;
    getDetectionHistoryByTcpRatio(): Promise<Array<FeatureSummary>>;
    getDetectionHistoryByUdpRatio(): Promise<Array<FeatureSummary>>;
    getDetectionHistoryTimestamps(): Promise<Array<Time>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { AttackType as _AttackType, DetectionEvent as _DetectionEvent, FeatureSummary as _FeatureSummary, RiskLevel as _RiskLevel, Time as _Time, TrafficClassification as _TrafficClassification, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearDetectionHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearDetectionHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearDetectionHistory();
            return result;
        }
    }
    async detectTraffic(arg0: FeatureSummary): Promise<TrafficClassification> {
        if (this.processError) {
            try {
                const result = await this.actor.detectTraffic(arg0);
                return from_candid_TrafficClassification_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.detectTraffic(arg0);
            return from_candid_TrafficClassification_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDetectionHistory(): Promise<Array<DetectionEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetectionHistory();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetectionHistory();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDetectionHistoryByAttackType(): Promise<Array<AttackType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetectionHistoryByAttackType();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetectionHistoryByAttackType();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDetectionHistoryByBytes(): Promise<Array<FeatureSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetectionHistoryByBytes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetectionHistoryByBytes();
            return result;
        }
    }
    async getDetectionHistoryByDestinationPortRange(): Promise<Array<FeatureSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetectionHistoryByDestinationPortRange();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetectionHistoryByDestinationPortRange();
            return result;
        }
    }
    async getDetectionHistoryByDuration(): Promise<Array<FeatureSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetectionHistoryByDuration();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetectionHistoryByDuration();
            return result;
        }
    }
    async getDetectionHistoryByIcmpRatio(): Promise<Array<FeatureSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetectionHistoryByIcmpRatio();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetectionHistoryByIcmpRatio();
            return result;
        }
    }
    async getDetectionHistoryByPackets(): Promise<Array<FeatureSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetectionHistoryByPackets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetectionHistoryByPackets();
            return result;
        }
    }
    async getDetectionHistoryByRiskLevel(): Promise<Array<RiskLevel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetectionHistoryByRiskLevel();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetectionHistoryByRiskLevel();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDetectionHistoryBySourcePortRange(): Promise<Array<FeatureSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetectionHistoryBySourcePortRange();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetectionHistoryBySourcePortRange();
            return result;
        }
    }
    async getDetectionHistoryByTcpRatio(): Promise<Array<FeatureSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetectionHistoryByTcpRatio();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetectionHistoryByTcpRatio();
            return result;
        }
    }
    async getDetectionHistoryByUdpRatio(): Promise<Array<FeatureSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetectionHistoryByUdpRatio();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetectionHistoryByUdpRatio();
            return result;
        }
    }
    async getDetectionHistoryTimestamps(): Promise<Array<Time>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetectionHistoryTimestamps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetectionHistoryTimestamps();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_AttackType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttackType): AttackType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_DetectionEvent_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DetectionEvent): DetectionEvent {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TrafficClassification_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrafficClassification): TrafficClassification {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    featureSummary: _FeatureSummary;
    timestamp: _Time;
    classification: _TrafficClassification;
}): {
    featureSummary: FeatureSummary;
    timestamp: Time;
    classification: TrafficClassification;
} {
    return {
        featureSummary: value.featureSummary,
        timestamp: value.timestamp,
        classification: from_candid_TrafficClassification_n3(_uploadFile, _downloadFile, value.classification)
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    attackType: _AttackType;
    riskLevel: _RiskLevel;
}): {
    attackType: AttackType;
    riskLevel: RiskLevel;
} {
    return {
        attackType: from_candid_AttackType_n5(_uploadFile, _downloadFile, value.attackType),
        riskLevel: from_candid_RiskLevel_n7(_uploadFile, _downloadFile, value.riskLevel)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dos: null;
} | {
    r2l: null;
} | {
    u2r: null;
} | {
    normal: null;
} | {
    probe: null;
}): AttackType {
    return "dos" in value ? AttackType.dos : "r2l" in value ? AttackType.r2l : "u2r" in value ? AttackType.u2r : "normal" in value ? AttackType.normal : "probe" in value ? AttackType.probe : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): RiskLevel {
    return "low" in value ? RiskLevel.low : "high" in value ? RiskLevel.high : "critical" in value ? RiskLevel.critical : "medium" in value ? RiskLevel.medium : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DetectionEvent>): Array<DetectionEvent> {
    return value.map((x)=>from_candid_DetectionEvent_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttackType>): Array<AttackType> {
    return value.map((x)=>from_candid_AttackType_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RiskLevel>): Array<RiskLevel> {
    return value.map((x)=>from_candid_RiskLevel_n7(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
