/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FeatureSummary = IDL.Record({
  'duration' : IDL.Nat,
  'destinationPortRange' : IDL.Nat,
  'packets' : IDL.Nat,
  'sourcePortRange' : IDL.Nat,
  'protocolTcpRatio' : IDL.Float64,
  'protocolIcmpRatio' : IDL.Float64,
  'protocolUdpRatio' : IDL.Float64,
  'bytes' : IDL.Nat,
});
export const AttackType = IDL.Variant({
  'dos' : IDL.Null,
  'r2l' : IDL.Null,
  'u2r' : IDL.Null,
  'normal' : IDL.Null,
  'probe' : IDL.Null,
});
export const RiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const TrafficClassification = IDL.Record({
  'attackType' : AttackType,
  'riskLevel' : RiskLevel,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const DetectionEvent = IDL.Record({
  'featureSummary' : FeatureSummary,
  'timestamp' : Time,
  'classification' : TrafficClassification,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearDetectionHistory' : IDL.Func([], [], []),
  'detectTraffic' : IDL.Func([FeatureSummary], [TrafficClassification], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDetectionHistory' : IDL.Func([], [IDL.Vec(DetectionEvent)], ['query']),
  'getDetectionHistoryByAttackType' : IDL.Func(
      [],
      [IDL.Vec(AttackType)],
      ['query'],
    ),
  'getDetectionHistoryByBytes' : IDL.Func(
      [],
      [IDL.Vec(FeatureSummary)],
      ['query'],
    ),
  'getDetectionHistoryByDestinationPortRange' : IDL.Func(
      [],
      [IDL.Vec(FeatureSummary)],
      ['query'],
    ),
  'getDetectionHistoryByDuration' : IDL.Func(
      [],
      [IDL.Vec(FeatureSummary)],
      ['query'],
    ),
  'getDetectionHistoryByIcmpRatio' : IDL.Func(
      [],
      [IDL.Vec(FeatureSummary)],
      ['query'],
    ),
  'getDetectionHistoryByPackets' : IDL.Func(
      [],
      [IDL.Vec(FeatureSummary)],
      ['query'],
    ),
  'getDetectionHistoryByRiskLevel' : IDL.Func(
      [],
      [IDL.Vec(RiskLevel)],
      ['query'],
    ),
  'getDetectionHistoryBySourcePortRange' : IDL.Func(
      [],
      [IDL.Vec(FeatureSummary)],
      ['query'],
    ),
  'getDetectionHistoryByTcpRatio' : IDL.Func(
      [],
      [IDL.Vec(FeatureSummary)],
      ['query'],
    ),
  'getDetectionHistoryByUdpRatio' : IDL.Func(
      [],
      [IDL.Vec(FeatureSummary)],
      ['query'],
    ),
  'getDetectionHistoryTimestamps' : IDL.Func([], [IDL.Vec(Time)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FeatureSummary = IDL.Record({
    'duration' : IDL.Nat,
    'destinationPortRange' : IDL.Nat,
    'packets' : IDL.Nat,
    'sourcePortRange' : IDL.Nat,
    'protocolTcpRatio' : IDL.Float64,
    'protocolIcmpRatio' : IDL.Float64,
    'protocolUdpRatio' : IDL.Float64,
    'bytes' : IDL.Nat,
  });
  const AttackType = IDL.Variant({
    'dos' : IDL.Null,
    'r2l' : IDL.Null,
    'u2r' : IDL.Null,
    'normal' : IDL.Null,
    'probe' : IDL.Null,
  });
  const RiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const TrafficClassification = IDL.Record({
    'attackType' : AttackType,
    'riskLevel' : RiskLevel,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const DetectionEvent = IDL.Record({
    'featureSummary' : FeatureSummary,
    'timestamp' : Time,
    'classification' : TrafficClassification,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearDetectionHistory' : IDL.Func([], [], []),
    'detectTraffic' : IDL.Func([FeatureSummary], [TrafficClassification], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDetectionHistory' : IDL.Func([], [IDL.Vec(DetectionEvent)], ['query']),
    'getDetectionHistoryByAttackType' : IDL.Func(
        [],
        [IDL.Vec(AttackType)],
        ['query'],
      ),
    'getDetectionHistoryByBytes' : IDL.Func(
        [],
        [IDL.Vec(FeatureSummary)],
        ['query'],
      ),
    'getDetectionHistoryByDestinationPortRange' : IDL.Func(
        [],
        [IDL.Vec(FeatureSummary)],
        ['query'],
      ),
    'getDetectionHistoryByDuration' : IDL.Func(
        [],
        [IDL.Vec(FeatureSummary)],
        ['query'],
      ),
    'getDetectionHistoryByIcmpRatio' : IDL.Func(
        [],
        [IDL.Vec(FeatureSummary)],
        ['query'],
      ),
    'getDetectionHistoryByPackets' : IDL.Func(
        [],
        [IDL.Vec(FeatureSummary)],
        ['query'],
      ),
    'getDetectionHistoryByRiskLevel' : IDL.Func(
        [],
        [IDL.Vec(RiskLevel)],
        ['query'],
      ),
    'getDetectionHistoryBySourcePortRange' : IDL.Func(
        [],
        [IDL.Vec(FeatureSummary)],
        ['query'],
      ),
    'getDetectionHistoryByTcpRatio' : IDL.Func(
        [],
        [IDL.Vec(FeatureSummary)],
        ['query'],
      ),
    'getDetectionHistoryByUdpRatio' : IDL.Func(
        [],
        [IDL.Vec(FeatureSummary)],
        ['query'],
      ),
    'getDetectionHistoryTimestamps' : IDL.Func([], [IDL.Vec(Time)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };