/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AttackType = { 'dos' : null } |
  { 'r2l' : null } |
  { 'u2r' : null } |
  { 'normal' : null } |
  { 'probe' : null };
export interface DetectionEvent {
  'featureSummary' : FeatureSummary,
  'timestamp' : Time,
  'classification' : TrafficClassification,
}
export interface FeatureSummary {
  'duration' : bigint,
  'destinationPortRange' : bigint,
  'packets' : bigint,
  'sourcePortRange' : bigint,
  'protocolTcpRatio' : number,
  'protocolIcmpRatio' : number,
  'protocolUdpRatio' : number,
  'bytes' : bigint,
}
export type RiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type Time = bigint;
export interface TrafficClassification {
  'attackType' : AttackType,
  'riskLevel' : RiskLevel,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearDetectionHistory' : ActorMethod<[], undefined>,
  'detectTraffic' : ActorMethod<[FeatureSummary], TrafficClassification>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDetectionHistory' : ActorMethod<[], Array<DetectionEvent>>,
  'getDetectionHistoryByAttackType' : ActorMethod<[], Array<AttackType>>,
  'getDetectionHistoryByBytes' : ActorMethod<[], Array<FeatureSummary>>,
  'getDetectionHistoryByDestinationPortRange' : ActorMethod<
    [],
    Array<FeatureSummary>
  >,
  'getDetectionHistoryByDuration' : ActorMethod<[], Array<FeatureSummary>>,
  'getDetectionHistoryByIcmpRatio' : ActorMethod<[], Array<FeatureSummary>>,
  'getDetectionHistoryByPackets' : ActorMethod<[], Array<FeatureSummary>>,
  'getDetectionHistoryByRiskLevel' : ActorMethod<[], Array<RiskLevel>>,
  'getDetectionHistoryBySourcePortRange' : ActorMethod<
    [],
    Array<FeatureSummary>
  >,
  'getDetectionHistoryByTcpRatio' : ActorMethod<[], Array<FeatureSummary>>,
  'getDetectionHistoryByUdpRatio' : ActorMethod<[], Array<FeatureSummary>>,
  'getDetectionHistoryTimestamps' : ActorMethod<[], Array<Time>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];